# Generated by Django 4.0.4 on 2022-05-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_usercategory_category_subscribers_alter_post_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='categoryThrough',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='postThrough',
            new_name='post',
        ),
    ]
