# Generated by Django 4.0.4 on 2022-05-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_categorythrough_postcategory_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='category',
            new_name='categoryThrough',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='post',
            new_name='postThrough',
        ),
    ]
