# Generated by Django 4.0.4 on 2022-05-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_bspostcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bspostcategory',
            old_name='categoryThrough',
            new_name='bscategoryThrough',
        ),
        migrations.RenameField(
            model_name='bspostcategory',
            old_name='postThrough',
            new_name='bspostThrough',
        ),
    ]
