# Generated by Django 4.0.4 on 2022-05-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_delete_bspostcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
        migrations.DeleteModel(
            name='UserCategory',
        ),
    ]
